const DOM = {};
const AppState = { type: 'plan', goal: 'lose', duration: '30', location: 'home', level: 'intermediate', extra: '', currentContent: '', records: [] };
function initDOM() { DOM.goal = document.getElementById('goal'); DOM.duration = document.getElementById('duration'); DOM.location = document.getElementById('location'); DOM.level = document.getElementById('level'); DOM.extra = document.getElementById('extra'); DOM.btnGenerate = document.getElementById('btn-generate'); DOM.resultArea = document.getElementById('result-area'); DOM.content = document.getElementById('content'); DOM.historyPanel = document.getElementById('history-panel'); DOM.historyList = document.getElementById('history-list'); DOM.historyOverlay = document.getElementById('history-overlay'); DOM.settingsModal = document.getElementById('settings-modal'); DOM.toast = document.getElementById('toast'); }
function initEvents() {
    document.querySelectorAll('.type-btn').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.type-btn').forEach(b => b.classList.remove('active')); btn.classList.add('active'); AppState.type = btn.dataset.type; }));
    DOM.goal.addEventListener('change', () => AppState.goal = DOM.goal.value);
    DOM.duration.addEventListener('change', () => AppState.duration = DOM.duration.value);
    DOM.location.addEventListener('change', () => AppState.location = DOM.location.value);
    DOM.level.addEventListener('change', () => AppState.level = DOM.level.value);
    DOM.extra.addEventListener('input', () => AppState.extra = DOM.extra.value);
    DOM.btnGenerate.addEventListener('click', generate);
    document.getElementById('btn-save').addEventListener('click', saveRecord);
    document.getElementById('btn-history').addEventListener('click', () => { DOM.historyPanel.classList.add('open'); DOM.historyOverlay.classList.remove('hidden'); });
    document.getElementById('btn-close-history').addEventListener('click', closeHistory); DOM.historyOverlay.addEventListener('click', closeHistory);
    document.getElementById('btn-settings').addEventListener('click', () => { DOM.settingsModal.classList.add('show'); loadSettings(); });
    document.getElementById('btn-close-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-cancel-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-save-settings').addEventListener('click', saveSettings);
    document.querySelectorAll('.example-btn').forEach(btn => btn.addEventListener('click', () => loadExample(btn.dataset.example)));
}
const EXAMPLES = { hiit: { goal: 'lose', duration: '20', location: 'home', extra: 'HIIT高强度间歇训练' }, abs: { goal: 'muscle', duration: '15', location: 'home', extra: '专门练腹肌' }, yoga: { goal: 'flex', duration: '30', location: 'home', extra: '瑜伽放松拉伸' }, upper: { goal: 'muscle', duration: '45', location: 'gym', extra: '上肢力量训练' } };
function loadExample(key) { const ex = EXAMPLES[key]; if (!ex) return; DOM.goal.value = ex.goal; AppState.goal = ex.goal; DOM.duration.value = ex.duration; AppState.duration = ex.duration; DOM.location.value = ex.location; AppState.location = ex.location; DOM.extra.value = ex.extra; AppState.extra = ex.extra; showToast('info', '已填入', '点击生成方案'); }
async function generate() { DOM.resultArea.classList.remove('hidden'); DOM.content.innerHTML = ''; AppState.currentContent = ''; await AIService.generate(AppState.type, AppState, (t) => { AppState.currentContent += t; DOM.content.innerHTML = formatContent(AppState.currentContent); }, () => showToast('success', '方案生成完成', ''), (e) => showToast('error', '生成失败', e.message)); }
function formatContent(text) { return text.replace(/^### (.+)$/gm, '<div class="exercise-card"><h3 class="font-bold text-orange-700">$1</h3>').replace(/^## (.+)$/gm, '<h2 class="text-xl font-bold text-gray-800 mt-5 mb-2">$1</h2>').replace(/\*\*(.+?)\*\*/g, '<strong class="text-orange-600">$1</strong>').replace(/\n(?=###)/g, '</div>\n').replace(/\n/g, '<br>'); }
async function saveRecord() { if (!AppState.currentContent) { showToast('warning', '无内容', ''); return; } const record = { type: AppState.type, goal: AppState.goal, content: AppState.currentContent }; const result = await StorageService.saveRecord(record); if (result.success) { showToast('success', '已保存', result.cloudSync ? '已同步云端' : '本地保存'); loadHistory(); } }
async function loadHistory() { AppState.records = await StorageService.getRecords(); renderHistory(); }
function renderHistory() { if (AppState.records.length === 0) { DOM.historyList.innerHTML = '<p class="text-gray-400 text-sm text-center">暂无记录</p>'; return; } const goalLabels = { lose: '减脂', muscle: '增肌', health: '健体', flex: '柔韧' }; DOM.historyList.innerHTML = AppState.records.map(r => `<div class="p-3 bg-orange-50 rounded-xl"><div class="font-medium text-gray-700">🏋️ ${goalLabels[r.goal] || '训练'}</div><div class="text-xs text-gray-400 mt-1">${new Date(r.createdAt).toLocaleDateString()}</div></div>`).join(''); }
function closeHistory() { DOM.historyPanel.classList.remove('open'); DOM.historyOverlay.classList.add('hidden'); }
function loadSettings() { const c = AIService.getModelConfig() || {}; document.getElementById('api-url').value = c.apiUrl || ''; document.getElementById('api-key').value = c.apiKey || ''; document.getElementById('model-name').value = c.modelName || ''; }
function saveSettings() { const c = { apiUrl: document.getElementById('api-url').value.trim(), apiKey: document.getElementById('api-key').value.trim(), modelName: document.getElementById('model-name').value.trim() || 'GLM-4-Flash' }; if (!c.apiUrl || !c.apiKey) { showToast('warning', '请填写完整', ''); return; } AIService.saveModelConfig(c); DOM.settingsModal.classList.remove('show'); showToast('success', '配置已保存', ''); }
function showToast(type, title, message) { const icons = { success: '✅', error: '❌', warning: '⚠️', info: 'ℹ️' }; const colors = { success: 'bg-green-500', error: 'bg-red-500', warning: 'bg-yellow-500', info: 'bg-orange-500' }; document.getElementById('toast-icon').className = `w-8 h-8 rounded-full flex items-center justify-center ${colors[type]}`; document.getElementById('toast-icon').textContent = icons[type]; document.getElementById('toast-title').textContent = title; document.getElementById('toast-message').textContent = message; DOM.toast.classList.remove('hidden'); setTimeout(() => DOM.toast.classList.add('hidden'), 3000); }
async function init() { initDOM(); initEvents(); await loadHistory(); const config = await AIService.initConfig(); if (!config) setTimeout(() => { DOM.settingsModal.classList.add('show'); showToast('info', '欢迎使用', '请配置 AI 模型'); }, 500); }
document.addEventListener('DOMContentLoaded', init);
